export enum Feature {
    AddWash = 'Drzwi AddWash™',
    AIControlPanel = 'Panel AI Control',
    InverterMotor = 'Silnik inwerterowy',
    ElectronicDisplay = 'Wyświetlacz elektroniczny',
    TouchDisplay = 'Wyświetlacz dotykowy',
}

export type WashingMachineType = {
    model: string
    type: string
    capacity: string
    color: string
    dimensions: string
    features: Feature[]
    price: number
    monthlyInstallment: number
    energyClass: string
    availability: string[]
    available: boolean
}

export const washingMachinesData = [
    {
        model: 'WW90T754ABT',
        type: 'Pralka QuickDrive™',
        capacity: '9 kg',
        color: 'biała',
        dimensions: '55 x 60 x 85 cm',
        features: [
            Feature.AddWash,
            Feature.AIControlPanel,
            Feature.InverterMotor,
            Feature.ElectronicDisplay,
        ],
        price: 3199,
        monthlyInstallment: 53.31,
        energyClass: 'A',
        availability: ['15.09.2022', '21.09.2022'],
        available: true,
    },
    {
        model: 'WW10T654DLH',
        type: 'Pralka EcoBubble™',
        capacity: '10.5 kg',
        color: 'biała',
        dimensions: '55 x 60 x 85 cm',
        features: [
            Feature.AddWash,
            Feature.AIControlPanel,
            Feature.InverterMotor,
            Feature.ElectronicDisplay,
        ],
        price: 3199,
        monthlyInstallment: 53.31,
        energyClass: 'A',
        availability: ['15.09.2022', '21.09.2022'],
        available: true,
    },
    {
        model: 'WW90T654DLH',
        type: 'Pralka EcoBubble™',
        capacity: '9 kg',
        color: 'biała',
        dimensions: '55 x 60 x 85 cm',
        features: [
            Feature.AddWash,
            Feature.AIControlPanel,
            Feature.InverterMotor,
            Feature.ElectronicDisplay,
        ],
        price: 3199,
        monthlyInstallment: 53.31,
        energyClass: 'A',
        availability: ['15.09.2022', '21.09.2022'],
        available: true,
    },
    {
        model: 'WW80T534ABT',
        type: 'Pralka QuickDrive™',
        capacity: '8 kg',
        color: 'biała',
        dimensions: '55 x 60 x 85 cm',
        features: [
            Feature.AddWash,
            Feature.AIControlPanel,
            Feature.InverterMotor,
            Feature.ElectronicDisplay,
        ],
        price: 2899,
        monthlyInstallment: 48.31,
        energyClass: 'B',
        availability: ['15.09.2022', '10.10.2022'],
        available: true,
    },
    {
        model: 'WW11T754ABX',
        type: 'Pralka QuickDrive™',
        capacity: '11 kg',
        color: 'czarna',
        dimensions: '60 x 65 x 85 cm',
        features: [
            Feature.AddWash,
            Feature.AIControlPanel,
            Feature.InverterMotor,
            Feature.TouchDisplay,
        ],
        price: 3499,
        monthlyInstallment: 58.31,
        energyClass: 'A',
        availability: ['15.09.2022', '10.10.2022'],
        available: true,
    },
    {
        model: 'WW70T554DTW',
        type: 'Pralka EcoBubble™',
        capacity: '7 kg',
        color: 'biała',
        dimensions: '50 x 55 x 85 cm',
        features: [
            Feature.InverterMotor,
            Feature.AIControlPanel,
            Feature.ElectronicDisplay,
        ],
        price: 2499,
        monthlyInstallment: 41.65,
        energyClass: 'C',
        availability: ['15.09.2022', '25.09.2022'],
        available: true,
    },
    {
        model: 'WW12T684DLX',
        type: 'Pralka EcoBubble™',
        capacity: '12 kg',
        color: 'srebrna',
        dimensions: '65 x 65 x 85 cm',
        features: [
            Feature.AddWash,
            Feature.InverterMotor,
            Feature.TouchDisplay,
            Feature.AIControlPanel,
        ],
        price: 3899,
        monthlyInstallment: 64.98,
        energyClass: 'A',
        availability: ['15.09.2022', '05.10.2022'],
        available: true,
    },
    {
        model: 'WW90T534DLH',
        type: 'Pralka QuickDrive™',
        capacity: '9 kg',
        color: 'biała',
        dimensions: '55 x 60 x 85 cm',
        features: [
            Feature.AIControlPanel,
            Feature.InverterMotor,
            Feature.ElectronicDisplay,
        ],
        price: 2999,
        monthlyInstallment: 49.98,
        energyClass: 'B',
        availability: ['15.09.2022', '18.09.2022'],
        available: true,
    },
    {
        model: 'WW85T654DLE',
        type: 'Pralka EcoBubble™',
        capacity: '8.5 kg',
        color: 'biała',
        dimensions: '55 x 60 x 85 cm',
        features: [
            Feature.AddWash,
            Feature.AIControlPanel,
            Feature.InverterMotor,
            Feature.ElectronicDisplay,
        ],
        price: 3099,
        monthlyInstallment: 51.65,
        energyClass: 'A',
        availability: ['15.09.2022', '22.09.2022'],
        available: true,
    },
    {
        model: 'WW10T754DLE',
        type: 'Pralka QuickDrive™',
        capacity: '10 kg',
        color: 'biała',
        dimensions: '55 x 60 x 85 cm',
        features: [
            Feature.AddWash,
            Feature.InverterMotor,
            Feature.AIControlPanel,
            Feature.ElectronicDisplay,
        ],
        price: 3299,
        monthlyInstallment: 54.98,
        energyClass: 'A',
        availability: ['15.09.2022', '20.09.2022'],
        available: true,
    },
    {
        model: 'WW90T554DLH',
        type: 'Pralka EcoBubble™',
        capacity: '9 kg',
        color: 'czarna',
        dimensions: '55 x 60 x 85 cm',
        features: [
            Feature.AddWash,
            Feature.AIControlPanel,
            Feature.InverterMotor,
            Feature.TouchDisplay,
        ],
        price: 3199,
        monthlyInstallment: 53.31,
        energyClass: 'A',
        availability: ['15.09.2022', '25.09.2022'],
        available: true,
    },
]
